nwnserver:
  image: jakkn/nwnx2-linuxserver:slim

  working_dir: /opt/nwnserver/

  volumes:
    - /opt/nwn/data:/opt/nwnserver/data
    - /opt/nwn/erf:/opt/nwnserver/erf
    - /opt/nwn/hak:/opt/nwnserver/hak
    - /opt/nwn/modules:/opt/nwnserver/modules
    - /opt/nwn/servervault:/opt/nwnserver/servervault
    - /opt/nwn/tlk:/opt/nwnserver/tlk

  command: ./compose-nwnstartup.sh
    -publicserver 1
    -servername "Containerized nwnx2-linuxserver"
    -dmpassword dmpw
    -oneparty 0
    -pvp 0
    -difficulty 2
    -elc 1
    -reloadwhenempty 0
    -module "module"
    -maxclients 32
    -servervault 1
    -maxlevel 40
    -gametype 0
    -autosaveinterval 0

  ports:
    - "5122:5121/tcp"
    - "5122:5121/udp"
  expose:
    - "5121"

  restart: always
  stdin_open: true
  tty: true
